[package]
name = "exagon"
version = "0.1.0"
authors = ["ocramh <ocramh11@gmail.com>"]
edition = "2018"

[dependencies]
rand = "^0.3"
tindercrypt = "0.2.2"
rust-crypto = "^0.2"
thiserror = "1.0.21"
anyhow = "1.0.33"
openssl = { version = "0.10", features = ["vendored"] }